"""empty message

Revision ID: 6d769a07c928
Revises: cdee3c824f96
Create Date: 2019-05-06 13:37:21.236489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d769a07c928'
down_revision = 'cdee3c824f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('fname', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('photo_link', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'photo_link')
    op.drop_column('users', 'name')
    op.drop_column('users', 'fname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
