"""empty message

Revision ID: b6a49594f125
Revises: 
Create Date: 2019-05-06 10:42:45.892333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a49594f125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'service_id')
    # ### end Alembic commands ###
